name: Build VLC 3.0.17.4 on Debian Bullseye

on:
  workflow_dispatch:

jobs:
  build-vlc:
    runs-on: ubuntu-22.04
    container:
      image: debian:bullseye
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
