name: Build VLC 3.0.17.4 on Debian Bullseye

on:
  workflow_dispatch:

jobs:
  build-vlc:
    runs-on: ubuntu-22.04  # We'll run Debian Bullseye via Docker for full compatibility
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull Debian Bullseye Docker
        run: docker pull debian:bullseye

      - name: Start Debian Bullseye container
        run: docker run --name vlc_build -dit -v ${{ github.workspace }}:/workspace debian:bullseye bash

      - name: Update and install dependencies
        run: |
          docker exec -i vlc_build bash -c "apt-get update && apt-get upgrade -y && \
            DEBIAN_FRONTEND=noninteractive apt-get install -y \
            build-essential pkg-config autoconf automake libtool git wget curl \
            yasm nasm cmake meson ninja-build intltool libtool-bin python3 python3-pip \
            liba52-0.7.4-dev libbluray-dev libdvdnav-dev libdvdread-dev libdvbpsi-dev \
            libxcb-shm0-dev libxcb-xv0-dev libxcb1-dev libx11-dev libxext-dev \
            libxinerama-dev libxrandr-dev libxv-dev libva-dev libvdpau-dev libgles2-mesa-dev \
            libwayland-dev wayland-protocols libgcrypt20-dev libgnutls28-dev libmad0-dev \
            libvorbis-dev libogg-dev libflac-dev libfaad-dev libmpg123-dev libopus-dev \
            libtheora-dev libspeex-dev libsndfile1-dev libpulse-dev libjack-jackd2-dev \
            libasound2-dev libavcodec-dev libavformat-dev libswscale-dev libavutil-dev \
            libpostproc-dev libvpx-dev libx264-dev libx265-dev libnuma-dev zlib1g-dev \
            libfribidi-dev libfreetype6-dev libfontconfig1-dev libharfbuzz-dev \
            libpango1.0-dev libsdl2-dev libmodplug-dev libdvd-pkg"

      - name: Download VLC 3.0.17.4 source
        run: |
          docker exec -i vlc_build bash -c "cd /workspace && \
            wget https://download.videolan.org/pub/videolan/vlc/3.0.17.4/vlc-3.0.17.4.tar.xz && \
            tar xf vlc-3.0.17.4.tar.xz"

      - name: Configure, compile, and build VLC
        run: |
          docker exec -i vlc_build bash -c "cd /workspace/vlc-3.0.17.4 && \
            ./configure --prefix=/workspace/vlc-build --enable-static --enable-shared && \
            make -j\$(nproc) && \
            make install"

      - name: Upload VLC build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: vlc-build
          path: vlc-build
