name: Build VLC 3.0.17.4 on Debian Bullseye

on:
  workflow_dispatch:

jobs:
  build-vlc:
    runs-on: ubuntu-22.04
    container:
      image: debian:bullseye
    env:
      DEBIAN_FRONTEND: noninteractive
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          set -euxo pipefail
          apt-get update
          apt-get upgrade -y
          apt-get install -y build-essential pkg-config autoconf automake libtool git wget curl \
            yasm nasm cmake meson ninja-build intltool libtool-bin python3 python3-pip \
            lua5.2 liblua5.2-dev \
            liba52-0.7.4-dev libbluray-dev libdvdnav-dev libdvdread-dev libdvbpsi-dev \
            libxcb-shm0-dev libxcb-xv0-dev libxcb1-dev libx11-dev libxext-dev \
            libxinerama-dev libxrandr-dev libxv-dev libva-dev libvdpau-dev libgles2-mesa-dev \
            libwayland-dev wayland-protocols libgcrypt20-dev libgnutls28-dev libmad0-dev \
            libvorbis-dev libogg-dev libflac-dev libfaad-dev libmpg123-dev libopus-dev \
            libtheora-dev libspeex-dev libsndfile1-dev libpulse-dev libjack-jackd2-dev \
            libasound2-dev libavcodec-dev libavformat-dev libswscale-dev libavutil-dev \
            libpostproc-dev libvpx-dev libx264-dev libx265-dev libnuma-dev zlib1g-dev \
            libfribidi-dev libfreetype6-dev libfontconfig1-dev libharfbuzz-dev \
            libpango1.0-dev libsdl2-dev libmodplug-dev
          apt-get clean

      - name: Download VLC 3.0.17.4 source
        run: |
          set -euxo pipefail
          cd "$GITHUB_WORKSPACE"
          wget --progress=dot:giga https://download.videolan.org/pub/videolan/vlc/3.0.17.4/vlc-3.0.17.4.tar.xz
          tar xf vlc-3.0.17.4.tar.xz

      - name: Configure, compile, and build VLC
        run: |
          set -euxo pipefail
          cd "$GITHUB_WORKSPACE/vlc-3.0.17.4"
          ./configure --prefix="$GITHUB_WORKSPACE/vlc-build" --enable-static --enable-shared 2>&1 | tee "$GITHUB_WORKSPACE/vlc-configure.log"
          make -j$(nproc) 2>&1 | tee "$GITHUB_WORKSPACE/vlc-make.log"
          make install 2>&1 | tee "$GITHUB_WORKSPACE/vlc-makeinstall.log"
          ls -la "$GITHUB_WORKSPACE/vlc-build" || true

      - name: Upload build artifacts and logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vlc-build-and-logs
          path: |
            vlc-build
            vlc-configure.log
            vlc-make.log
            vlc-makeinstall.log
            vlc-3.0.17.4/config.log
