name: Build VLC 3.0.17.4 on Debian Bullseye

on:
  workflow_dispatch:

jobs:
  build-vlc:
    runs-on: ubuntu-22.04  # We'll run Debian Bullseye via Docker for full compatibility
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Debian Bullseye Docker
        run: docker pull debi
